INT_TYPE = "INT_TYPE"
BOOL_TYPE = "BOOL_TYPE"

IF = "IF"
ELSE = "ELSE"
WHILE = "WHILE"
PRINT = "PRINT"
READ = "READ"

TRUE = "TRUE"
FALSE = "FALSE"

IDENT = "IDENT"
NUMBER = "NUMBER"

PLUS = "PLUS"
MINUS = "MINUS"
STAR = "STAR"
SLASH = "SLASH"

EQUAL = "EQUAL"
EQUAL_EQUAL = "EQUAL_EQUAL"
BANG_EQUAL = "BANG_EQUAL"

LESS = "LESS"
GREATER = "GREATER"

SEMICOLON = "SEMICOLON"

LEFT_PAREN = "LEFT_PAREN"
RIGHT_PAREN = "RIGHT_PAREN"

LEFT_BRACE = "LEFT_BRACE"
RIGHT_BRACE = "RIGHT_BRACE"

EOF = "EOF"

SINGLE_CHAR_TOKENS = {
    "+": PLUS,
    "-": MINUS,
    "*": STAR,
    ";": SEMICOLON,
    "(": LEFT_PAREN,
    ")": RIGHT_PAREN,
    "{": LEFT_BRACE,
    "}": RIGHT_BRACE,
    "<": LESS,
    ">": GREATER,
}
