PLUS = "PLUS"
MINUS = "MINUS"
STAR = "STAR"
SLASH = "SLASH"

SEMICOLON = "SEMICOLON"
LEFT_PAREN = "LEFT_PAREN"
RIGHT_PAREN = "RIGHT_PAREN"
LEFT_BRACE = "LEFT_BRACE"
RIGHT_BRACE = "RIGHT_BRACE"

LESS = "LESS"
GREATER = "GREATER"
EQUAL = "EQUAL"
EQUAL_EQUAL = "EQUAL_EQUAL"
BANG_EQUAL = "BANG_EQUAL"

NUMBER = "NUMBER"
STRING = "STRING"
IDENTIFIER = "IDENTIFIER"

INT = "INT"
BOOL = "BOOL"
IF = "IF"
ELSE = "ELSE"
WHILE = "WHILE"
TRUE = "TRUE"
FALSE = "FALSE"
PRINT = "PRINT"
READ = "READ"

EOF = "EOF"

SINGLE_CHAR_TOKENS = {
    "+": PLUS,
    "-": MINUS,
    "*": STAR,
    ";": SEMICOLON,
    "(": LEFT_PAREN,
    ")": RIGHT_PAREN,
    "{": LEFT_BRACE,
    "}": RIGHT_BRACE,
    "<": LESS,
    ">": GREATER,
}

KEYWORDS = {
    "int": INT,
    "bool": BOOL,
    "if": IF,
    "else": ELSE,
    "while": WHILE,
    "true": TRUE,
    "false": FALSE,
    "print": PRINT,
    "read": READ,
}
